config/routes.rb
Rails.application.routes.draw do
  resources :accounts do
    collection { post :import }
  end
  resources :recodes
  resources :categories

  get 'articles/show'
  resources :articles do
    get 'import', :on => :collection
  end
  # devise
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root to: 'accounts#index', as: :authenticated_root
    end

    unauthenticated do
      root to: "devise/sessions#new", as: :unauthenticated_root
    end
  end
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
  validates :name, presence: true
  validates :account_type, presence: true
  has_many :recodes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :recodes
  belongs_to :user


end

app/models/recode.rb
class Recode < ApplicationRecord
  belongs_to :account, optional: true
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :accounts
  has_many :categories
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  
  def index
    # @accounts= Account.all
    # current_user.accounts
    # (simple jo user login ha is ka data show)
     @accounts= current_user.accounts
  end

  def show
    @account = Account.find(params[:id])
    @recodes = @account.recodes
    # =================================


    @credit_amount  = 0
    @debit_amount = 0
    total_amount = 0
    @recodes.each do |recode|
      puts "record_id #{recode.id}"
      puts "amount #{recode.amount}" #tb used kerty hn jb string my rekh vana ho
      total_amount =  total_amount + recode.amount.to_i
      if  recode.recode_type == "income"
        @credit_amount  = @credit_amount +  recode.amount.to_i

      elsif recode.recode_type == "expence"

        @debit_amount  = @debit_amount + recode.amount.to_i
      end

    end
    puts "total_amount #{total_amount}"

    # =================================
    @starting_balacne = @account.amount
    @account_balance = (@starting_balacne + @credit_amount) - @debit_amount
  #  @recodes = @account.recodes account kya data ko recodes main show ker vaya
  end

  def new
    @account = Account.new
  end

  def create
    @account = Account.new(account_params)
    # @account.color = "Black"
    if @account.save
      redirect_to action: "index"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
      @account = Account.find(params[:id])
  end

  def update
      account = Account.find(params[:id])
      if account.update(account_params)
        redirect_to action: "index"
      else
        render :edit, status: :unprocessable_entity
      end
  end

  def destroy
    account = Account.find(params[:id])
    account.destroy
    #redirect_to action: "index" menes proivide root ab wapis index per chala jay
    redirect_to action: "index", :notice => "Account record deleted"
  end

  def import
    # file =  File.read('/home/hassan/Downloads/meezan/AccountFullStatement.CSV')
    @accounts = current_user.accounts
    account_id = params[:account_id]


    file = params[:file]
    csv = File.read(file)

    CSV.parse(csv, headers: true).each do |row|
      des = row["Description"]
      category_name = des.split[0..1].join(' ')
      #split used for get two words
      category = Category.where(name: category_name)

      if category.blank?
        Category.create(name: category_name, user_id: current_user.id)
        category = Category.where(name: category_name)
      end
      category_id = category.first.id
      #where
      recode_type = ""
      amount = 0

      if row["Debit"].present?
      recode_type = "expence"
       amount = row["Debit"]
      elsif row["Credit"].present?
        recode_type = "income"
        amount = row["Credit"]
      end

      # row = Recode.new(date_time: row["Transaction"],note: row["Description"], amount: amount, account_id: account_id,recode_type: recode_type )
      Recode.create(date_time: row["Transaction"],note: row["Description"], amount: amount, account_id: account_id,category_id: category_id ,recode_type: recode_type )
      end

    # Record.new(asdfs,sdf, acount_id: account_id)


    redirect_to action: "index", notice: "Products imported."
  end

  private
  def account_params
    params.require(:account).permit(:name, :account_type, :amount, :currency, :user_id).merge("currency": "PKR")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  def index
    @account = Account.new

  end
  
  def about
  
  end

  def new
    @account = Account.new
  end



  def import
  # render "articles/about"
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = current_user.categories
  end

  def show
    @category = Category.find(params[:id])
    @recodes = @category.recodes
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to @category
    else
      render :new, status: :unprocessable_entity
    end
  end
  def edit
    @category = Category.find(params[:id])
    @accounts = current_user.accounts
  end

  def update
    category = Category.find(params[:id])
    if category.update(category_params)
      redirect_to action: "index", controller: "categories"
    else
      render :edit, status: :unprocessable_entity
    end
  end


  def destroy
    category = Category.find(params[:id])
    category.destroy
    #redirect_to action: "index" menes proivide root ab wapis index per chala jay
    redirect_to action: "index", :notice => "Account record deleted"
  end

  private
  def category_params
    params.require(:category).permit(:name, :user_id)
  end
end

app/controllers/recodes_controller.rb
class RecodesController < ApplicationController
  def index
    @recodes = current_user.accounts.map{|account| account.recodes}.flatten
    # [1, 2, [23, 25], [3, 6]]
    # 3.0.0 :009 > a.flatten
    # => [1, 2, 23, 25, 3, 6]
    @accounts= current_user.accounts
  end

  def show
    @recode = Recode.find(params[:id])

  end

  def new
    @recode = Recode.new
    @accounts = current_user.accounts
    @categories = current_user.categories
  #  @recode varibel hi used hoga na ky `recodes` form <%= form_with model: @recodes do |form| %>
  end

  def create
    @recode = Recode.new(recode_params)
    # @account.color = "Black"
    if @recode.save
      redirect_to action: "index", controller: "accounts"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @recode = Recode.find(params[:id])
    @accounts = current_user.accounts
    @categories = Category.all

  end

  def update
    recode = Recode.find(params[:id])
    if recode.update(recode_params)
      redirect_to action: "index", controller: "accounts"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    recode = Recode.find(params[:id])
    recode.destroy
    #redirect_to action: "index" menes proivide root ab wapis index per chala jay
    redirect_to action: "index", :notice => "Account record deleted"
  end

    # file = File.read('/home/hassan/Downloads/meezan/AccountFullStatement.CSV')
  # exit
  # exit! (exit from looop)

  private
  def recode_params
    params.require(:recode).permit(:category_id, :recode_type, :amount, :date_time, :note, :account_id )
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/recodes_helper.rb
module RecodesHelper
end

app/views/accounts/_form.html.erb
<% @account.errors.full_messages_for(:name).each do |message| %>
  <div><%= message %></div>
<% end %>
<div class="row justify-content-center">
<div class="col-md-4 border rounded p-4 bg-success text-white shadow-lg">
<%= form_for  @account do |form|  %>
    <h5 style="text-align: center"> <%= type %> Account</h5>

  <div class="form-group mb-3">
    <%= form.label :name %><br>
    <%= form.text_field :name, placeholder: "Enter your Name" ,class: 'form-control' %>
  </div>

  <div class="form-group ">
    <%= form.label :account_type %><br>
    <%= form.text_field :account_type, placeholder: "Account Type",class: 'form-control mt-2 mb-2'  %>
  </div>

  <div class="form-group mt-3 mb-3">
    <%= form.label :starting_balance  ,class: 'mt-2'%><br>
    <%= form.text_field :amount, placeholder: "Amount",class: 'form-control' %>
  </div>

  <div>
    <%= form.number_field :user_id, value: current_user.id, type: :hidden %>
  </div>
    <div class="text-center">
      <button type="submit" class="btn btn-block mt-2 btn-outline-warning"> <%= type=="Edit"? "Update" : "Create" %> Account</button>
    </div>
<!--  <button type="submit" class="btn mt-4 btn-primary">  <%#= type %> Account </button>-->
<% end %>
</div>
</div>

app/views/accounts/edit.html.erb
<h1>Edit Account</h1>
<%= render "form", type: "Edit" %>

app/views/accounts/index.html.erb
<h1 style="text-align: center;">Accounts List</h1>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp"
        crossorigin="anonymous">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB"
        crossorigin="anonymous">
  <link rel="stylesheet" href="css/Account.css">
  <title>Bootstrap Theme</title>


  <style>
    body{
    }
      .filter-result .job-box {
          -webkit-box-shadow: 0 0 35px 0 rgba(130, 130, 130, 0.2);
          box-shadow: 0 0 35px 0 rgba(130, 130, 130, 0.2);
          border-radius: 10px;
          padding: 10px 35px;
      }


      .job-box .img-holder {
          height: 65px;
          width: 65px;
          background-color: #4e63d7;
          background-image: -webkit-gradient(linear, left top, right top, from(rgba(78, 99, 215, 0.9)), to(#5a85dd));
          background-image: linear-gradient(to right, rgba(78, 99, 215, 0.9) 0%, #5a85dd 100%);
          font-family: "Open Sans", sans-serif;
          color: #fff;
          font-size: 22px;
          font-weight: 700;
          display: -webkit-box;
          display: -ms-flexbox;
          display: flex;
          -webkit-box-pack: center;
          -ms-flex-pack: center;
          justify-content: center;
          -webkit-box-align: center;
          -ms-flex-align: center;
          align-items: center;
          border-radius: 65px;
      }
  </style>

</head>

<body>
<div class="container-fluid mt-3">
  <div class="row">
    <div class="col-md-2 border" style="height: 500px;">

      <h2 class="font-weight-bold mt-4">Account</h2>

      <button class="btn btn-success  btn-block  mt-4" style="border-radius:13px ;"> <i class="fas mr-1 py-2  p fa-plus"></i><%= link_to "Add Account", new_account_path, class: 'text-white'%></button>
      <button class="btn btn-success  btn-block  mt-4" style="border-radius:13px ;"> <i class="fas mr-1 py-2  p fa-plus"></i><%= link_to "Add Recode", new_recode_path, class: 'text-white'%></button>
      <button class="btn btn-success  btn-block  mt-4" style="border-radius:13px ;"> <i class="fas mr-1 py-2  p fa-plus"></i><%= link_to "Add Category", new_category_path, class: 'text-white'%></button>

    </div>
    <div class="col-md-10">
    <% @accounts.each do |account| %>

      <div class="filter-result">
        <div class="job-box d-md-flex align-items-center justify-content-between mb-3" >
          <div class="job-left  d-md-flex align-items-center flex-wrap">
            <div class="img-holder mr-md-4 mb-md-0 mb-4 mx-auto mx-md-0 d-md-none d-lg-flex">
              <i class="fas fa-wallet"></i>
            </div>
            <h5 class="text-center text-md-left" style="font-size: 20px;"><%= account.name %></h5>
          </div>

          <div>
            <p class="text-muted"><%= account.account_type %></p>
          </div>

          <div class=" d-flex">
            <p><%= account.amount %></p>
 
              <div class="dropdown">
              <i class='fa ml-2 fa-ellipsis-v' style="cursor: pointer" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false"></i>

            <!-- <ul class="dropdown-menu bg-dark" aria-labelledby="dropdownMenuButton1"> -->
              <!-- <li> -->
                <%= link_to "Show", account_path(account.id), class:"dropdown-item bg-success"%>
                
              <!-- </li> -->
              <!-- <li> -->
                <%= link_to "Edit", edit_account_path(account.id), class:"dropdown-item bg-primary" %>
                <%= link_to "Delete", account_path(account.id), class:"dropdown-item bg-danger" ,data: {
                    turbo_method: :delete, turbo_confirm: "Are you sure?"}, :method => :delete %>
                      
                    <!-- </li> -->
              <!-- </ul> -->

              </div>

          </div>

        </div>

      </div>

    <% end %>
    </div>
  </div>
</div>





<script src="http://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
        crossorigin="anonymous"></script>
</body>
</html>

app/views/accounts/new.html.erb
<%= render "form", type: "Add"%>

app/views/accounts/show.html.erb
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true%>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>


<body style="background-image: url('https://cdn.pixabay.com/photo/2017/09/05/10/08/office-2717014_960_720.jpg');background-repeat:no-repeat;background-size: cover">

<div class="container">
  <div class="row">

    <div class="col-sm">
      <div class="card">
        <div class="card-header bg-danger">Add Record</div>
        <div class="card-body">
          <%= link_to "+ Add Single Recode", new_recode_path,class:'actions btn btn-outline-dark' %>
          <br>
          <br>
          <h3>Import Recode</h3>
          <%= form_tag import_accounts_path, multipart: true do %>
            <%= file_field_tag :file  %>
            <%= hidden_field_tag :account_id,@account.id %><br><br>
            <button type="submit" class='actions btn btn-outline-dark'> +Import </button>
          <% end %>
        </div>
      </div>
    </div>

    <div class="col-sm">
      <div class="card">
        <div class="card-header bg-info">Account details</div>
        <div class="card-body">

          <div class="row">
          <div class="col">
            <h5>Name: </h5>
          </div>
          <div class="col">
            <h8> <%= @account.name%></h8>
          </div>
        </div>

          <div class="row">
            <div class="col">
              <h5>Account Type: </h5>
            </div>
            <div class="col">
              <h8>  <%= @account.account_type%></h8>
            </div>
          </div>

          <div class="row">
            <div class="col">
              <h4>Amount:  </h4>
            </div>
            <div class="col">
              <h8> <%= @account.amount%></h8>
            </div>
          </div>

          <div class="row">
            <div class="col">
              <h4>Name: </h4>
            </div>
            <div class="col">
              <h8> <%= @account.name%></h8>
            </div>
          </div>

          <div class="row">
            <div class="col">
              <h4>currency: </h4>
            </div>
            <div class="col">
              <h8> <%= @account.currency%></h8>
            </div>
          </div>

        </div>
      </div>

    </div>

    <div class="col-sm">
      <div class="card">
        <div class="card-header bg-success">Balance details</div>
        <div class="card-body">

          <div class="row">
            <div class="col">
              <h5>Account_balance: </h5>
            </div>
            <div class="col">
              <h8> <%= @account_balance%></h8>
            </div>
          </div>

          <div class="row">
            <div class="col">
              <h5>starting_balacne: </h5>
            </div>
            <div class="col">
              <h8> <%= @account.amount%></h8>
            </div>
          </div>

          <div class="row">
            <div class="col">
              <h5>income: </h5>
            </div>
            <div class="col">
              <h8>  <%= @credit_amount%></h8>
            </div>
          </div>

          <div class="row">
            <div class="col">
              <h5>expence: </h5>
            </div>
            <div class="col">
              <h8> <%= @debit_amount%></h8>
            </div>
          </div>
        </div>
      </div>

    </div>

  </div>
</div>


a





<h3 style="color: black"></h3>






      <h3>Account Recodes</h3>

<table class="table table-success">
  <thead class="table-dark">
  <tr>
    <th scope="col">ID</th>
    <th scope="col">Account</th>
    <th scope="col">Recode_type</th>
    <th scope="col">Amount</th>
    <th scope="col">Date Time</th>
    <th scope="col">Category</th>
    <th scope="col">Note</th>
    <th scope="col">Action</th>
  </tr>
  </thead>
  <% unless  @recodes.blank? %>
  <% @recodes.each do |recode| %>
    <div class="field">
      <!--    <#= link_to account.name, account %>-->
      <!--    #how to link href  -->
      <tbody>
      <tr>
        <td scope="row"><%= recode.id  %></td>
        <td><%= recode.account.name %></td>
        <td><%= recode.recode_type %></td>
        <td><%= recode.amount %></td>
        <td><%= recode.date_time&.strftime('%B %e at %l:%M %p')%></td>
        <td><%= recode.category_id   %></td>
        <td><%= recode.note %></td>

        <!--      here we define account.id and bacause this provide to edit and delete -->
        <td>
          <%= link_to "Show", recode_path(recode.id), class: "btn btn-success" %>
          <%= link_to "Edit", edit_recode_path(recode.id), class: "btn btn-primary" %>
          <%= link_to "Delete", recode_path(recode.id), class: "btn btn-danger" ,data: {
              turbo_method: :delete, turbo_confirm: "Are you sure?"}, :method => :delete %>
        </td>
      </tr>
      </tbody>
    </div>
  <% end %>
  <% end %>
  </table>
</body>

app/views/articles/_header.html.erb
<nav class="navbar navbar-expand-lg bg-dark navbar-dark"  style="background-color: #e3f2fd;">
  <i class="fas fa-wallet fa-2x text-white"></i>
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-4 mb-lg-0">
        <li><img src="https://i.pinimg.com/564x/01/02/0a/01020a1e22984f8a6183ba18f06dc361.jpg" alt="" width="30" height="24" class="d-inline-block align-text-top">
        </li>
          <% if user_signed_in? %>  
        <li class="nav-item" >
        <%= link_to 'Dashboard', articles_path , class: "nav-link active" %>
        </li>

        <li  class="nav-item">
        	<%= link_to "Account" , accounts_path , class: "nav-link"%>
         <!-- articles_about_path ya vo path bata raha jis per jana ha is ny -->
        </li>

        <li class="nav-item">
          <%= link_to "Records" , recodes_path, class: "nav-link"%>
        </li>

        <li class="nav-item">
          <%= link_to "Category" , categories_path, class: "nav-link"%>
        </li>

        <li class="nav-item">
          <%= link_to "import" , accounts_url , class: "nav-link"%>
        </li>
        <% end %>
        <div class="ml-5">
         <li class="nav-item active ">
            <% if user_signed_in? %>

                <%= link_to 'sign out', destroy_user_session_path, method: :delete, class: "btn btn-outline-success" %>

             </li>
             </div>


         <% else %>


        <li class="navbar-nav mr-auto">
          <%= link_to "Sign up" , new_user_registration_path , class: "nav-link"%>
         <!-- articles_about_path ya vo path bata raha jis per jana ha is ny -->
        </li>

        <li class="nav-item">
          <%= link_to "Sign in" , new_user_session_path , class: "nav-link"%>
         <!-- articles_about_path ya vo path bata raha jis per jana ha is ny -->
        </li>

         <% end %>




        <!-- <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
         --><!-- <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li> -->
      </ul>
<!--      <form class="d-flex">-->
<!--        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">-->
<!--        <button class="btn btn-outline-success" type="submit">Search</button>-->
<!--      </form>-->
    </div>
  </div>
</nav>

app/views/articles/index.html.erb
<%= link_to "+ Add account", new_account_path,  class:"btn btn-block mt-2 btn-outline-primary" %>

<%= link_to "+ Add Category", new_category_path,  class:"btn btn-block mt-2 btn-outline-primary" %>

<%= link_to "+ Add Recode", new_recode_path,  class:"btn btn-block mt-2 btn-outline-primary" %>

app/views/categories/_form.html.erb
<% @category.errors.full_messages_for(:name).each do |message| %>
  <div><%= message %></div>
<% end %>

<div class="row justify-content-center">
  <div class="col-md-4 border rounded p-4 bg-success text-white shadow-lg">
<%= form_for @category do |form| %>
      <h5 class="lead text-center"> <%= type %> Category</h5>
  <div class="form-group mt-3 mb-3">
    <%= form.label :name %><br>
    <%= form.text_field :name,placeholder: "Enter a Name "%>
  </div>

  <div>
    <%= form.number_field :user_id, value: current_user.id, type: :hidden %>
  </div>
  <div class="text-center">
    <button type="submit" class="btn btn-block mt-2 btn-outline-warning"><%= type %> Category</button>
  </div>
<% end %>
  </div>
</div>

app/views/categories/edit.html.erb
<h1>Edit Category</h1>
<%= render "form", type: "Update" %>

app/views/categories/new.html.erb
<%= render "form", type: "New" %>

app/views/categories/show.html.erb
<body style="background-image: url('https://cdn.pixabay.com/photo/2021/03/13/04/11/touch-screen-6091015_960_720.jpg');background-repeat:no-repeat;background-size: cover">
<h3>Recodes</h3>

<table class="table table-success">
  <thead class="table-dark">
      <tr>
         <th scope="col">Name</th>
        <th scope="col">Action</th>
      </tr>
  </thead>

  <tbody>
     <td><%= @category.name %></td><td>
       <%= link_to "Edit",edit_category_path(@category.id), class: "btn btn-primary" %>
       <%= link_to "Delete", category_path(@category.id), class: "btn btn-danger" ,data: {
           turbo_method: :delete, turbo_confirm: "Are you sure?"}, :method => :delete %>
     </td>

  </tbody>
</table>
<style>
    tr:hover {
        background-color:antiquewhite;
    }
</style>

<table class="table table-hover table-light">
  <thead class="table table-dark	">
  <tr>
    <th scope="col">ID</th>
    <th scope="col">Recode_type</th>
    <th scope="col">Amount</th>
    <th scope="col">Account</th>
    <th scope="col">Category</th>
    <th scope="col">Date Time</th>
    <th scope="col">Note</th>
    <th scope="col">Action</th>
  </tr>
  </thead>
  <% @recodes.each do |recode| %>
    <div class="field">
      <!--    <#= link_to account.name, account %>-->
      <!--    #how to link href  -->
      <tbody>
      <tr>
        <th scope="row"><%= recode.id  %></th>
        <td><%= recode.recode_type %></td>
        <td><%= recode.amount %></td>
        <td><%= recode.account_id %></td>
        <td><%= recode.category_id %></td>
        <td><%= recode.date_time&.strftime('%B %e at %l:%M %p')%></td>
        <td><%= recode.note %></td>
        <!--      here we define account.id and bacause this provide to edit and delete -->
        <td>
          <%= link_to "Show", recode_path(recode.id), class: "btn btn-success" %>
          <%= link_to "Edit", edit_recode_path(recode.id), class: "btn btn-primary" %>
          <%= link_to "Delete", recode_path(recode.id), class: "btn btn-danger" ,data:
              { turbo_method: :delete, turbo_confirm: "Are you sure?"}, :method => :delete %>
        </td>
      </tr>
      </tbody>
    </div>
  <% end %>
</table>
</body>

app/views/recodes/edit.html.erb
<h1>Edit Recode</h1>
<%= render "form", recode: @recode, type: "Update" %>
<!--type hm ny choose ki ha Update ki ha jb be _form my jay ga edit sy then _form per show hoga update -->
<!--or new.html per be update ki bejay new likh dain gain
reocode varibel ky ander @variable ki value reakh rahy hn -->

app/views/recodes/show.html.erb
<!--table class="table table-hover">-->
<body style="background-image: url('https://cdn.pixabay.com/photo/2021/01/11/19/16/briquette-5909427_960_720.jpg');background-repeat:no-repeat;background-size: cover">

<table class="table table-light">
  <thead class="table-dark">
    <tr>

      <th scope="col">Category</th>
      <th scope="col">Recode_type</th>
      <th scope="col">Amount</th>
      <th scope="col">Account ID</th>
      <th scope="col">date time</th>
      <th scope="col">Note</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @recode.category_id %></td>
      <td><%= @recode.recode_type %></td>
      <td><%= @recode.amount %></td>
      <td><%= @recode.account_id %></td>
      <td><%= @recode.date_time&.strftime('%B %e at %l:%M %p')%></td>
      <td><%= @recode.note %></td>

      <!--      here we define account.id and bacause this provide to edit and delete -->
      <td>
        <%= link_to "Edit", edit_recode_path(@recode.id), class: "btn btn-primary" %>
        <%= link_to "Delete", recode_path(@recode.id), class: "btn btn-danger" ,data: {
        turbo_method: :delete, turbo_confirm: "Are you sure?"}, :method => :delete %>
      </td>
    </tr>
  </tbody>
</table>
</body>